version: '2'
services:
    kukulkan-app:
        image: kukulkan
        depends_on: 
            - kukulkan-mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://kukulkan-mongodb:27017
            - KUKULKAN_DATA_MYSQL_URI=jdbc:mysql://kukulkan-mysql:3306
        ports:
            - 8080:8080
    kukulkan-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/kukulkancraftsman/mongodb/:/data/db/
